/**
 * Context generator — extracts manifest data and produces agent-injectable context.
 *
 * This is the core of `manifest wrap`. It reads an AIM manifest and produces
 * structured context text that can be injected into any agent platform.
 */

import { readFileSync, existsSync } from "node:fs";
import { extname, resolve, dirname } from "node:path";
import yaml from "js-yaml";
import type {
  ManifestContext,
  InjectedRule,
  KnowledgeUnit,
  CapabilityIndex,
  GovernanceRuleSummary,
  WrapSection,
} from "./types.js";

/**
 * Load a manifest and extract all context needed for wrapping.
 */
export function extractManifestContext(
  manifestPath: string,
  environmentOverride?: string,
): ManifestContext {
  const resolvedPath = resolve(manifestPath);
  if (!existsSync(resolvedPath)) {
    throw new Error(`Manifest not found: ${resolvedPath}`);
  }

  const content = readFileSync(resolvedPath, "utf-8");
  const ext = extname(resolvedPath).toLowerCase();

  let manifest: Record<string, unknown>;
  if (ext === ".json") {
    manifest = JSON.parse(content);
  } else {
    manifest = yaml.load(content) as Record<string, unknown>;
  }

  const metadata = (manifest.metadata ?? {}) as Record<string, unknown>;
  const context = (manifest.context ?? {}) as Record<string, unknown>;
  const governance = (manifest.governance ?? {}) as Record<string, unknown>;
  const knowledge = (manifest.knowledge ?? []) as Array<Record<string, unknown>>;
  const capabilities = (manifest.capabilities ?? []) as Array<Record<string, unknown>>;
  const rules = (governance.rules ?? []) as Array<Record<string, unknown>>;
  const qualityGates = (governance.quality_gates ?? {}) as Record<string, unknown>;

  const environment = environmentOverride ?? (context.environment as string | undefined);

  // Extract injected rules (context injection — not static/semantic enforcement)
  const injectedRules: InjectedRule[] = rules
    .filter((r) => {
      const enforcement = r.enforcement;
      return enforcement === "injected";
    })
    .map((r) => ({
      name: r.name as string,
      instruction: r.instruction as string,
      severity: (r.severity as string) ?? "info",
    }));

  // Extract knowledge units, sorted by priority
  const knowledgeUnits: KnowledgeUnit[] = knowledge
    .map((k) => ({
      name: k.name as string,
      trigger: (k.trigger as string) ?? "",
      content: (k.content as string) ?? "",
      priority: (k.priority as number) ?? 0,
    }))
    .sort((a, b) => b.priority - a.priority);

  // Extract capability Tier 0 indexes
  const capabilityIndexes: CapabilityIndex[] = capabilities.map((c) => ({
    name: c.name as string,
    description: c.description as string | undefined,
    tags: c.tags as string[] | undefined,
  }));

  // Summarize all governance rules for awareness
  const governanceRules: GovernanceRuleSummary[] = rules.map((r) => {
    const enforcement = r.enforcement;
    let enforcementStr: string;
    if (typeof enforcement === "string") {
      enforcementStr = enforcement;
    } else if (enforcement && typeof enforcement === "object") {
      const e = enforcement as { primary?: string; fallback?: string };
      enforcementStr = e.primary ?? "unknown";
    } else {
      enforcementStr = "unknown";
    }

    return {
      name: r.name as string,
      action: (r.action as string) ?? "log",
      severity: (r.severity as string) ?? "info",
      enforcement: enforcementStr,
      message: r.message as string | undefined,
    };
  });

  return {
    metadata: {
      name: (metadata.name as string) ?? "unknown",
      version: (metadata.version as string) ?? "0.0.0",
      description: (metadata.description as string) ?? "",
    },
    persona: context.persona as string | undefined,
    domain: context.domain as string | undefined,
    environment,
    injectedRules,
    knowledgeUnits,
    qualityGates,
    capabilities: capabilityIndexes,
    governanceRules,
  };
}

/**
 * Generate the context injection text from a ManifestContext.
 * Returns { text, sections } where sections tracks what was included.
 */
export function generateContextText(ctx: ManifestContext): {
  text: string;
  sections: WrapSection[];
} {
  const lines: string[] = [];
  const sections: WrapSection[] = [];

  function section(name: string, content: string[]): void {
    if (content.length === 0) return;
    const startLine = lines.length;
    lines.push(...content);
    lines.push("");
    sections.push({ name, lineCount: lines.length - startLine });
  }

  // Header
  section("header", [
    `# AIM Governance: ${ctx.metadata.name} v${ctx.metadata.version}`,
    `# Generated by \`manifest wrap\` — DO NOT EDIT MANUALLY`,
    `# Source: aim.yaml | Protocol: AIM 1.0`,
    "",
  ]);

  // Persona & Context
  if (ctx.persona || ctx.domain || ctx.environment) {
    const contextLines: string[] = ["## Context"];
    if (ctx.persona) {
      contextLines.push(`You are: ${ctx.persona}`);
    }
    if (ctx.domain) {
      contextLines.push(`Domain: ${ctx.domain}`);
    }
    if (ctx.environment) {
      contextLines.push(`Environment: ${ctx.environment}`);
    }
    section("context", contextLines);
  }

  // Governance Rules Awareness
  if (ctx.governanceRules.length > 0) {
    const ruleLines: string[] = [
      "## Active Governance Rules",
      "",
      "The following rules are enforced on your output. Violations will be caught by the enforcement engine.",
      "",
    ];

    // Group by enforcement type
    const staticRules = ctx.governanceRules.filter(
      (r) => r.enforcement === "static",
    );
    const semanticRules = ctx.governanceRules.filter(
      (r) => r.enforcement === "semantic",
    );
    const injectedRules = ctx.governanceRules.filter(
      (r) => r.enforcement === "injected",
    );

    if (staticRules.length > 0) {
      ruleLines.push(
        `### Static (enforced post-output — ${staticRules.length} rules)`,
      );
      for (const r of staticRules) {
        const badge = r.action === "block" ? "BLOCKS" : r.action.toUpperCase();
        ruleLines.push(`- **${r.name}** [${badge}] ${r.message ?? ""}`);
      }
      ruleLines.push("");
    }

    if (semanticRules.length > 0) {
      ruleLines.push(
        `### Semantic (LLM-as-judge — ${semanticRules.length} rules)`,
      );
      for (const r of semanticRules) {
        ruleLines.push(`- **${r.name}** [${r.action.toUpperCase()}] ${r.message ?? ""}`);
      }
      ruleLines.push("");
    }

    if (injectedRules.length > 0) {
      ruleLines.push(`### Guidelines (${injectedRules.length} rules)`);
      ruleLines.push(
        "These are advisory rules. Follow them unless there is a strong reason not to.",
      );
      ruleLines.push("");
    }

    section("governance-awareness", ruleLines);
  }

  // Injected Rules (full instructions)
  if (ctx.injectedRules.length > 0) {
    const instrLines: string[] = ["## Instructions"];
    for (const rule of ctx.injectedRules) {
      instrLines.push("");
      instrLines.push(`### ${rule.name}`);
      instrLines.push(rule.instruction.trim());
    }
    section("injected-instructions", instrLines);
  }

  // Quality Gates
  const gateEntries = Object.entries(ctx.qualityGates);
  if (gateEntries.length > 0) {
    const gateLines: string[] = ["## Quality Gates"];
    for (const [domain, gates] of gateEntries) {
      gateLines.push("");
      gateLines.push(`### ${domain}`);
      if (gates && typeof gates === "object") {
        for (const [key, value] of Object.entries(
          gates as Record<string, unknown>,
        )) {
          const displayKey = key.replace(/_/g, " ");
          if (Array.isArray(value)) {
            gateLines.push(`- **${displayKey}**: ${value.join(", ")}`);
          } else {
            gateLines.push(`- **${displayKey}**: ${String(value)}`);
          }
        }
      }
    }
    section("quality-gates", gateLines);
  }

  // Knowledge Units
  if (ctx.knowledgeUnits.length > 0) {
    const knowledgeLines: string[] = [
      "## Knowledge",
      "",
      "Load the following knowledge when the trigger conditions are met.",
      "",
    ];
    for (const unit of ctx.knowledgeUnits) {
      knowledgeLines.push(`### ${unit.name}`);
      if (unit.trigger) {
        knowledgeLines.push(`**When:** ${unit.trigger}`);
      }
      knowledgeLines.push("");
      knowledgeLines.push(unit.content.trim());
      knowledgeLines.push("");
    }
    section("knowledge", knowledgeLines);
  }

  // Capabilities (Tier 0 index only)
  if (ctx.capabilities.length > 0) {
    const capLines: string[] = [
      "## Available Capabilities",
      "",
    ];
    for (const cap of ctx.capabilities) {
      let line = `- **${cap.name}**`;
      if (cap.description) line += `: ${cap.description}`;
      if (cap.tags && cap.tags.length > 0)
        line += ` [${cap.tags.join(", ")}]`;
      capLines.push(line);
    }
    section("capabilities", capLines);
  }

  // Footer
  section("footer", [
    "---",
    `*AIM governance active. ${ctx.governanceRules.length} rules loaded. Run \`manifest enforce\` to validate output.*`,
  ]);

  return { text: lines.join("\n"), sections };
}
