import { resolve, join } from "node:path";
import { existsSync, writeFileSync, chmodSync, mkdirSync, readFileSync } from "node:fs";
import chalk from "chalk";

const PRE_COMMIT_HOOK = `#!/bin/sh
# AIM Enforcement Pre-Commit Hook
# Generated by manifest hooks install

# Get list of staged files
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMR)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

# Run manifest enforce on staged files
echo "🔒 Running AIM governance checks..."

# Create temp file with staged file list
TEMP_FILE=$(mktemp)
echo "$STAGED_FILES" > "$TEMP_FILE"

# Run enforce with exit-on-block
npx manifest enforce . --staged 2>&1

EXIT_CODE=$?

rm -f "$TEMP_FILE"

if [ $EXIT_CODE -ne 0 ]; then
  echo ""
  echo "❌ Commit blocked by AIM governance rules."
  echo "   Fix the violations above, then try again."
  echo ""
  echo "   To bypass (not recommended): git commit --no-verify"
  exit 1
fi

echo "✅ AIM governance checks passed"
exit 0
`;

const COMMIT_MSG_HOOK = `#!/bin/sh
# AIM Commit Message Hook
# Generated by manifest hooks install

# Read commit message
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Check for minimum length
MSG_LEN=\${#COMMIT_MSG}
if [ $MSG_LEN -lt 10 ]; then
  echo "❌ Commit message too short (minimum 10 characters)"
  exit 1
fi

exit 0
`;

export async function hooksCommand(
  action: "install" | "uninstall" | "status",
  options: { force?: boolean; type?: string },
): Promise<void> {
  const gitDir = resolve(".git");
  const hooksDir = join(gitDir, "hooks");

  // Check we're in a git repo
  if (!existsSync(gitDir)) {
    console.error(chalk.red("\n  ✗ Not a git repository\n"));
    console.error(chalk.dim("  Run this command from the root of a git repository.\n"));
    process.exit(1);
  }

  // Check manifest exists
  if (!existsSync(resolve("aim.yaml"))) {
    console.error(chalk.red("\n  ✗ No aim.yaml found\n"));
    console.error(chalk.dim(`  Run ${chalk.white("manifest init")} first to create a manifest.\n`));
    process.exit(1);
  }

  switch (action) {
    case "install":
      await installHooks(hooksDir, options);
      break;
    case "uninstall":
      await uninstallHooks(hooksDir);
      break;
    case "status":
      await showHookStatus(hooksDir);
      break;
  }
}

async function installHooks(
  hooksDir: string,
  options: { force?: boolean; type?: string },
): Promise<void> {
  console.log(chalk.dim("\n  Installing AIM git hooks...\n"));

  // Ensure hooks directory exists
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  const hookTypes = options.type?.split(",") ?? ["pre-commit"];
  let installed = 0;

  for (const hookType of hookTypes) {
    const hookPath = join(hooksDir, hookType.trim());
    const hookContent = getHookContent(hookType.trim());

    if (!hookContent) {
      console.log(chalk.yellow(`  ⚠ Unknown hook type: ${hookType}`));
      continue;
    }

    // Check if hook already exists
    if (existsSync(hookPath) && !options.force) {
      const existing = readFileSync(hookPath, "utf-8");
      if (!existing.includes("AIM")) {
        console.log(chalk.yellow(`  ⚠ ${hookType} hook exists (non-AIM). Use --force to overwrite.`));
        continue;
      }
    }

    // Write hook
    writeFileSync(hookPath, hookContent, "utf-8");
    chmodSync(hookPath, "755");
    console.log(chalk.green(`  ✓ Installed ${chalk.white(hookType)} hook`));
    installed++;
  }

  if (installed > 0) {
    console.log();
    console.log(chalk.dim("  AIM governance will now run automatically before each commit."));
    console.log(chalk.dim("  Blocking violations will prevent commits.\n"));
    console.log(chalk.dim("  To bypass (emergencies only):"));
    console.log(chalk.dim(`    ${chalk.white("git commit --no-verify")}\n`));
  } else {
    console.log(chalk.dim("\n  No hooks installed.\n"));
  }
}

async function uninstallHooks(hooksDir: string): Promise<void> {
  console.log(chalk.dim("\n  Uninstalling AIM git hooks...\n"));

  const hookTypes = ["pre-commit", "commit-msg"];
  let removed = 0;

  for (const hookType of hookTypes) {
    const hookPath = join(hooksDir, hookType);

    if (!existsSync(hookPath)) {
      continue;
    }

    const content = readFileSync(hookPath, "utf-8");
    if (!content.includes("AIM")) {
      console.log(chalk.dim(`  • ${hookType}: not an AIM hook, skipping`));
      continue;
    }

    // Remove hook by writing empty file
    writeFileSync(hookPath, "#!/bin/sh\nexit 0\n", "utf-8");
    console.log(chalk.green(`  ✓ Removed ${chalk.white(hookType)} hook`));
    removed++;
  }

  if (removed > 0) {
    console.log(chalk.dim("\n  AIM hooks have been removed.\n"));
  } else {
    console.log(chalk.dim("  No AIM hooks found to remove.\n"));
  }
}

async function showHookStatus(hooksDir: string): Promise<void> {
  console.log(chalk.dim("\n  AIM Git Hook Status\n"));

  const hookTypes = ["pre-commit", "commit-msg"];

  for (const hookType of hookTypes) {
    const hookPath = join(hooksDir, hookType);

    if (!existsSync(hookPath)) {
      console.log(chalk.dim(`  • ${hookType}: ${chalk.red("not installed")}`));
      continue;
    }

    const content = readFileSync(hookPath, "utf-8");
    if (content.includes("AIM")) {
      console.log(`  • ${hookType}: ${chalk.green("active")}`);
    } else {
      console.log(chalk.dim(`  • ${hookType}: exists (non-AIM)`));
    }
  }

  console.log();
  console.log(chalk.dim("  Commands:"));
  console.log(chalk.dim(`    ${chalk.white("manifest hooks install")}   — Install hooks`));
  console.log(chalk.dim(`    ${chalk.white("manifest hooks uninstall")} — Remove hooks`));
  console.log();
}

function getHookContent(hookType: string): string | null {
  switch (hookType) {
    case "pre-commit":
      return PRE_COMMIT_HOOK;
    case "commit-msg":
      return COMMIT_MSG_HOOK;
    default:
      return null;
  }
}
